sudo: false
language: python
python:
  - "2.7"

install:
  - pip install -qr test-requirements.txt

script:
  - pep8 checkin2015/
  - coverage run --branch --source=checkin2015,leaderboard,retail,survey ./manage.py test --settings=checkin2015.dev
  - coverage report
